platform :ios, '8.0'
use_frameworks!

target 'podsExample' do
    #pod 'AFNetworking', '~> 2.6'
    pod 'SwiftHTTP', '~> 1.0.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'ObjectMapper', '~> 0.19'
end