# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'FoodTracker' do
	pod 'AlecrimCoreData', '~> 4.0'
    pod 'Alamofire', '~> 3.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'AlamofireImage', '~> 2.0'
    

end

target 'FoodTrackerTests' do

end

